config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'top#show'

  get 'login', to: 'sessions#new'
  post 'sessions', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :notes, path: 'n', param: 'number', only: %i[index show]

  namespace :admin do
    resources :notes
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
# frozen_string_literal: true

class Note < ApplicationRecord
  NUMBER_OF_CHARS_FOR_NUMBER = 16

  scope :published, -> { where.not(published_at: nil) }

  has_rich_text :content

  before_validation :set_uniq_number, unless: :number

  validates :number, presence: true, uniqueness: true
  validates :title, presence: true

  def to_param
    number
  end

  private

  def set_uniq_number
    num = nil
    loop do
      num = SecureRandom.alphanumeric(NUMBER_OF_CHARS_FOR_NUMBER)
      break unless self.class.exists?(number: num)
    end
    self.number = num
  end
end

app/models/session_form.rb
# frozen_string_literal: true

class SessionForm
  include ActiveModel::Model

  attr_accessor :login_id, :password

  def authenticate
    if login_id == ENV['LOGIN_ID'] && password == ENV['PASSWORD']
      true
    else
      errors.add :base, 'login failed'

      false
    end
  end
end

app/controllers/admin/notes_controller.rb
# frozen_string_literal: true

module Admin
  class NotesController < ApplicationController
    before_action :require_login
    before_action :set_note, only: %i[show edit update destroy]

    def index
      @notes = Note.all
    end

    def show; end

    def new
      @note = Note.new
    end

    def edit; end

    def create
      @note = Note.new(note_params)

      # TODO: Implement later!!!
      @note.published_at = Time.zone.now

      if @note.save
        redirect_to admin_note_url(@note), notice: 'Note was successfully created.'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @note.update(note_params)
        redirect_to admin_note_url(@note), notice: 'Note was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @note.destroy!

      redirect_to admin_notes_url, notice: 'Note was successfully destroyed.'
    end

    private

    def set_note
      @note = Note.find_by!(number: params[:id])
    end

    def note_params
      params.require(:note).permit(:note, :title, :content)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :logged_in?

  private

  def logged_in?
    session[:logged_in].present?
  end

  def require_login
    # hide pages
    raise ActionController::RoutingError, 'Not Found' unless logged_in?
  end
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

class NotesController < ApplicationController
  def index
    @notes = Note.first(3)
  end

  def show
    @note = Note.published.find_by!(number: params[:number])
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new
    @session_form = SessionForm.new
  end

  def create
    @session_form = SessionForm.new(session_form_params)
    if @session_form.authenticate
      session[:logged_in] = true

      redirect_to notes_path, notice: 'ログインした'
    else
      render :new
    end
  end

  def destroy
    session[:logged_in] = nil

    redirect_to root_path
  end

  private

  def session_form_params
    params.require(:session_form).permit(:login_id, :password)
  end
end

app/controllers/top_controller.rb
# frozen_string_literal: true

class TopController < ApplicationController
  def show; end
end

app/helpers/admin/notes_helper.rb
# frozen_string_literal: true

module Admin
  module NotesHelper
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/notes_helper.rb
# frozen_string_literal: true

module NotesHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/top_helper.rb
# frozen_string_literal: true

module TopHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/notes/_form.html.erb
<%= form_with(model: [:admin, note]) do |form| %>
  <% if note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <br />
    <%= form.label :content %>
    <%= form.rich_text_area :content %>

    <%= form.submit %>
  </div>
<% end %>

app/views/admin/notes/_note.html.erb
<article id="<%= dom_id note %>">
  <h1><%= note.title %></h1>
  <time><%= note.published_at %></time>
  <p><%= note.content %></p>
</article>

app/views/admin/notes/edit.html.erb
<h1>Editing note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Show this note", @note %> |
  <%= link_to "Back to notes", admin_notes_path %>
</div>

app/views/admin/notes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Notes</h1>

<div id="notes">
  <% @notes.each do |note| %>
    <p>
      <%= link_to note.title, admin_note_path(note) %>
    </p>
  <% end %>
</div>

<%= link_to "New note", new_admin_note_path %>

app/views/admin/notes/new.html.erb
<h1>New note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Back to notes", admin_notes_path %>
</div>

app/views/admin/notes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @note %>

<div>
  <%= link_to "Edit this note", edit_admin_note_path(@note) %> |
  <%= link_to "Back to notes", admin_notes_path %>

  <%= button_to "Destroy this note", admin_note_path(@note), method: :delete %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>tanaka51</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>

  <% if logged_in? %>
    <%= button_to 'ログアウト', logout_url, method: :delete %>
  <% end %>
</html>

app/views/notes/index.html.erb
<h1>ランダムに３つ記事が表示される</h1>
<ul>
  <% @notes.each do |note| %>
    <li><%= link_to note.title, note_url(note) %></li>
  <% end %>
</ul>

app/views/notes/show.html.erb
<article>
  <h1><%= @note.title %></h1>
  <time><%= @note.published_at %></time>
  <p><%= @note.content %></p>
</article>

app/views/top/show.html.erb
<h1>tanaka51</h1>
<dl>
  <dt>名前</dt><dd>田中洸一 @tanaka51</dd>
  <dt>仕事</dt><dd>株式会社万葉 CEO&CTO</dd>
  <dt>ブログ</dt><dd><%= link_to 'https://tanaka51.jp/n', 'https://tanaka51.jp/n' %></dd>
</dl>